/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/earth/earth.glb -t -r public 
*/

import * as THREE from 'three'
import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane001: THREE.Mesh
    Plane002: THREE.Mesh
    Plane003: THREE.Mesh
    Plane004: THREE.Mesh
    Plane005: THREE.Mesh
    Plane006: THREE.Mesh
    Plane007: THREE.Mesh
    Plane008: THREE.Mesh
    Plane009: THREE.Mesh
    Cube021: THREE.Mesh
    Cube030: THREE.Mesh
    Cube031: THREE.Mesh
    Cube032: THREE.Mesh
    Cube033: THREE.Mesh
    Cube034: THREE.Mesh
    Cube035: THREE.Mesh
    Cube036: THREE.Mesh
    Cube037: THREE.Mesh
    Cube038: THREE.Mesh
    Cube039: THREE.Mesh
    Cube040: THREE.Mesh
    Cube041: THREE.Mesh
    Cube042: THREE.Mesh
    Cube043: THREE.Mesh
    Cube044: THREE.Mesh
    Cube045: THREE.Mesh
    Cube046: THREE.Mesh
    Cube047: THREE.Mesh
    Cube048: THREE.Mesh
    Cube049: THREE.Mesh
    Cube050: THREE.Mesh
    Cube051: THREE.Mesh
    Cube052: THREE.Mesh
    Cube053: THREE.Mesh
    Cube054: THREE.Mesh
    Cube055: THREE.Mesh
    Icosphere003: THREE.Mesh
    Icosphere004: THREE.Mesh
    Icosphere005: THREE.Mesh
    Icosphere002: THREE.Mesh
    Icosphere006: THREE.Mesh
    Icosphere007: THREE.Mesh
    Icosphere008: THREE.Mesh
    Icosphere009: THREE.Mesh
    Icosphere010: THREE.Mesh
    Icosphere011: THREE.Mesh
    Icosphere012: THREE.Mesh
    Icosphere013: THREE.Mesh
    Cube: THREE.Mesh
    Icosphere001: THREE.Mesh
    Cube003: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    Cube011: THREE.Mesh
    Cube013: THREE.Mesh
    Cube014: THREE.Mesh
    Cube012: THREE.Mesh
    Cube015: THREE.Mesh
    Cube016: THREE.Mesh
    Cube017: THREE.Mesh
    Cube018: THREE.Mesh
    Cube019: THREE.Mesh
    Cube020: THREE.Mesh
    Cube022: THREE.Mesh
    Cube023: THREE.Mesh
    Cube024: THREE.Mesh
    Cube025: THREE.Mesh
    Cube026: THREE.Mesh
    Cube027: THREE.Mesh
    Cube028: THREE.Mesh
    Cube029: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: []
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Earth(props: JSX.IntrinsicElements['group']) {
  const [scale, setScale] = useState(window.innerWidth < 1080 ? 3.5 : 4.5);
  const [earthPosition, setPosition] = useState(window.innerWidth < 1080 ? [0,-25,0] : [0,-35,0]);
  useEffect(() => {
    const handleResize = () => {
      setScale(window.innerWidth < 1080 ? 3.5 : 5);
      setPosition(window.innerWidth < 1080 ? [0,-25,0] : [0,-35,0]);
    };

    // Add event listener on mount
    window.addEventListener('resize', handleResize);
    // Remove event listener on unmount
    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, []);

  const { nodes, materials } = useGLTF('/earth/earth.glb') as GLTFResult
  return (
    <group {...props} dispose={null} scale={scale} position={earthPosition} receiveShadow> 
      <mesh receiveShadow geometry={nodes.Plane001.geometry} material={materials['Material.001']} position={[6.647, 6.616, 1.948]} rotation={[0.158, -0.143, -1.469]} scale={0.184} />
      <mesh receiveShadow geometry={nodes.Plane002.geometry} material={materials['Material.001']} position={[6.62, 7.704, 1.502]} rotation={[0.178, -0.205, -1.356]} scale={0.184} />
      <mesh receiveShadow geometry={nodes.Plane003.geometry} material={materials['Material.001']} position={[6.763, 7.715, -0.562]} rotation={[0.133, 0.023, -1.401]} scale={0.184} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.001']} position={[2.341, 13.011, -0.712]} rotation={[-0.011, 0.206, -0.411]} scale={0.184} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.001']} position={[2.832, 12.624, -1.801]} rotation={[-0.069, 0.237, -0.561]} scale={0.184} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['Material.001']} position={[3.599, 12.431, 0.592]} rotation={[0.242, 0.044, -0.544]} scale={0.184} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['Material.001']} position={[-4.967, 2.863, 3.015]} rotation={[0.561, 0.697, 1.898]} scale={0.184} />
      <mesh geometry={nodes.Plane008.geometry} material={materials['Material.001']} position={[-4.9, 3.325, 3.585]} rotation={[0.556, 0.716, 1.588]} scale={0.184} />
      <mesh geometry={nodes.Plane009.geometry} material={materials['Material.001']} position={[-3.466, 1.4, 2.825]} rotation={[0.454, 0.938, 2.163]} scale={0.184} />
      <mesh geometry={nodes.Cube021.geometry} material={materials['Material.001']} position={[-5.746, 8.594, -4.166]} rotation={[-0.773, -0.294, 0.962]} scale={0.171} />
      <mesh geometry={nodes.Cube030.geometry} material={materials['Material.001']} position={[-5.966, 8.943, -3.612]} rotation={[-0.773, -0.294, 0.962]} scale={0.171} />
      <mesh geometry={nodes.Cube031.geometry} material={materials['Material.001']} position={[-5.608, 9.395, -3.913]} rotation={[-0.773, -0.294, 0.962]} scale={0.171} />
      <mesh geometry={nodes.Cube032.geometry} material={materials['Material.001']} position={[-6.292, 9.539, -2.442]} rotation={[-0.647, -0.077, 1.14]} scale={0.171} />
      <mesh geometry={nodes.Cube033.geometry} material={materials['Material.001']} position={[-6.39, 9.834, -1.874]} rotation={[-0.647, -0.077, 1.14]} scale={0.171} />
      <mesh geometry={nodes.Cube034.geometry} material={materials['Material.001']} position={[-6.132, 10.306, -2.19]} rotation={[-0.647, -0.077, 1.14]} scale={0.171} />
      <mesh geometry={nodes.Cube035.geometry} material={materials['Material.001']} position={[-3.988, 10.972, -4.35]} rotation={[-0.682, -0.118, 0.612]} scale={0.161} />
      <mesh geometry={nodes.Cube036.geometry} material={materials['Material.001']} position={[-4.122, 11.222, -3.956]} rotation={[-0.682, -0.118, 0.612]} scale={0.161} />
      <mesh geometry={nodes.Cube037.geometry} material={materials['Material.001']} position={[-3.717, 11.573, -3.995]} rotation={[-0.682, -0.118, 0.612]} scale={0.161} />
      <mesh geometry={nodes.Cube038.geometry} material={materials['Material.001']} position={[-3.311, 12.173, -3.485]} rotation={[-0.473, 0.02, 0.555]} scale={0.161} />
      <mesh geometry={nodes.Cube039.geometry} material={materials['Material.001']} position={[-3.38, 12.359, -3.015]} rotation={[-0.473, 0.02, 0.555]} scale={0.161} />
      <mesh geometry={nodes.Cube040.geometry} material={materials['Material.001']} position={[-2.935, 12.664, -2.967]} rotation={[-0.392, 0.023, 0.285]} scale={0.161} />
      <mesh geometry={nodes.Cube041.geometry} material={materials['Material.001']} position={[-1.595, 12.543, -4.09]} rotation={[-0.529, -0.001, 0.162]} scale={0.161} />
      <mesh geometry={nodes.Cube042.geometry} material={materials['Material.001']} position={[-1.611, 12.769, -3.697]} rotation={[-0.529, -0.001, 0.162]} scale={0.161} />
      <mesh geometry={nodes.Cube043.geometry} material={materials['Material.001']} position={[-1.33, 12.882, -3.595]} rotation={[-0.527, -0.008, 0.162]} scale={0.161} />
      <mesh geometry={nodes.Cube044.geometry} material={materials['Material.001']} position={[1.773, 8.484, 6.856]} rotation={[1.339, -0.211, -0.319]} scale={0.161} />
      <mesh geometry={nodes.Cube045.geometry} material={materials['Material.001']} position={[2.452, 8.14, 6.696]} rotation={[1.324, -0.207, -0.318]} scale={0.161} />
      <mesh geometry={nodes.Cube046.geometry} material={materials['Material.001']} position={[3.135, 7.922, 6.505]} rotation={[1.309, -0.276, -0.368]} scale={0.161} />
      <mesh geometry={nodes.Cube047.geometry} material={materials['Material.001']} position={[2.115, 9.616, 6.476]} rotation={[1.16, -0.174, -0.096]} scale={0.161} />
      <mesh geometry={nodes.Cube048.geometry} material={materials['Material.001']} position={[2.78, 9.313, 6.391]} rotation={[1.339, -0.212, -0.319]} scale={0.161} />
      <mesh geometry={nodes.Cube049.geometry} material={materials['Material.001']} position={[3.485, 8.986, 5.983]} rotation={[1.042, -0.159, -0.473]} scale={0.161} />
      <mesh geometry={nodes.Cube050.geometry} material={materials['Material.001']} position={[5.502, 8.741, -4.625]} rotation={[0.659, 0.524, -1.776]} scale={0.161} />
      <mesh geometry={nodes.Cube051.geometry} material={materials['Material.001']} position={[5.622, 8.213, -4.57]} rotation={[1.054, 0.415, -1.957]} scale={0.161} />
      <mesh geometry={nodes.Cube052.geometry} material={materials['Material.001']} position={[5.615, 7.465, -4.762]} rotation={[0.831, 0.594, -2.122]} scale={0.161} />
      <mesh geometry={nodes.Cube053.geometry} material={materials['Material.001']} position={[2.197, 11.441, -5.501]} rotation={[0.918, 1.073, -2.011]} scale={0.161} />
      <mesh geometry={nodes.Cube054.geometry} material={materials['Material.001']} position={[3.721, 10.295, -5.173]} rotation={[1.336, 0.933, -2.002]} scale={0.161} />
      <mesh geometry={nodes.Cube055.geometry} material={materials['Material.001']} position={[4.931, 9.224, -5.176]} rotation={[1.047, 0.987, -1.765]} scale={0.161} />
      <mesh geometry={nodes.Icosphere003.geometry} material={materials['Material.001']} position={[-0.162, 1.782, -5.484]} rotation={[-2.256, -0.153, 0.073]} scale={0.31} />
      <mesh geometry={nodes.Icosphere004.geometry} material={materials['Material.001']} position={[-1.831, 2.242, -5.646]} rotation={[-2.147, -0.139, 0.17]} scale={0.31} />
      <mesh geometry={nodes.Icosphere005.geometry} material={materials['Material.001']} position={[-1.837, 1.189, -4.579]} rotation={[-2.422, -0.205, 0.298]} scale={0.31} />
      <mesh geometry={nodes.Icosphere002.geometry} material={materials['Material.001']} position={[1.106, 16.414, -1.323]} rotation={[Math.PI, -1.449, Math.PI]} scale={0.295} />
      <mesh geometry={nodes.Icosphere006.geometry} material={materials['Material.001']} position={[-0.564, 16.414, -0.171]} rotation={[Math.PI, -1.449, Math.PI]} scale={0.295} />
      <mesh geometry={nodes.Icosphere007.geometry} material={materials['Material.001']} position={[-0.659, 16.85, 0.949]} rotation={[Math.PI, -1.449, Math.PI]} scale={0.295} />
      <mesh geometry={nodes.Icosphere008.geometry} material={nodes.Icosphere008.material} position={[-3.346, 9.227, -8.453]} rotation={[2.091, 0.761, 1.096]} scale={0.295} />
      <mesh geometry={nodes.Icosphere009.geometry} material={nodes.Icosphere009.material} position={[-5.016, 9.227, -7.301]} rotation={[1.217, -0.805, 2.192]} scale={0.295} />
      <mesh geometry={nodes.Icosphere010.geometry} material={nodes.Icosphere010.material} position={[-5.112, 9.662, -6.181]} rotation={[1.235, -0.78, 2.168]} scale={0.295} />
      <mesh geometry={nodes.Icosphere011.geometry} material={materials['Material.001']} position={[3.877, 3.639, 6.919]} rotation={[-2.972, 0.885, -0.836]} scale={0.295} />
      <mesh geometry={nodes.Icosphere012.geometry} material={materials['Material.001']} position={[2.207, 3.639, 8.071]} rotation={[-1.015, 0.335, -2.721]} scale={0.295} />
      <mesh geometry={nodes.Icosphere013.geometry} material={materials['Material.001']} position={[2.111, 4.075, 9.19]} rotation={[-1.745, 1.43, -2.32]} scale={0.295} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[-1.448, 14.158, 0]} scale={0.1} />
      <mesh geometry={nodes.Icosphere001.geometry} material={materials['Material.001']} position={[4.071, 5.634, -6.332]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.001']} position={[6.33, 10.22, 3.137]} rotation={[0.332, -0.285, -0.992]} scale={0.224} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.001']} position={[6.002, 10.83, 3.07]} rotation={[0.284, -0.225, -0.839]} scale={0.224} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.001']} position={[5.861, 10.542, 3.683]} rotation={[0.332, -0.285, -0.992]} scale={0.224} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.001']} position={[0.783, 14.655, 0.368]} rotation={[-0.007, -0.038, -0.141]} scale={0.307} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.001']} position={[0.737, 14.558, 1.25]} rotation={[0.095, -0.064, -0.099]} scale={0.307} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.001']} position={[4.434, 8.968, -7.037]} rotation={[0.325, 1.122, -1.48]} scale={0.307} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.001']} position={[6.662, 10.82, -3.281]} rotation={[0.342, 0.818, -1.063]} scale={0.307} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.001']} position={[-1.469, 12.589, -6.096]} rotation={[-2.857, 1.147, 2.084]} scale={0.307} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.001']} position={[5.794, 8.713, -6.343]} rotation={[0.371, 1.083, -1.821]} scale={0.307} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.001']} position={[0.433, 13.832, 3.49]} rotation={[0.341, -0.077, -0.208]} scale={0.307} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.001']} position={[0.635, 14.354, 2.443]} rotation={[0.151, -0.062, 0.045]} scale={0.307} />
      <mesh geometry={nodes.Cube017.geometry} material={materials['Material.001']} position={[4.689, 8.31, 6.627]} rotation={[-1.028, -1.095, -2.087]} scale={0.069} />
      <mesh geometry={nodes.Cube018.geometry} material={materials['Material.001']} position={[4.867, 8.477, 6.501]} rotation={[-0.94, -1.024, -2.156]} scale={0.069} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.001']} position={[5.083, 8.106, 6.499]} rotation={[-0.94, -1.024, -2.156]} scale={0.069} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.001']} position={[5.249, 9.278, 6.108]} rotation={[0.625, -0.192, -0.581]} scale={0.452} />
      <mesh geometry={nodes.Cube022.geometry} material={materials['Material.001']} position={[3.303, 6.711, 8.004]} rotation={[1.211, -0.499, -0.405]} scale={0.452} />
      <mesh geometry={nodes.Cube023.geometry} material={materials['Material.001']} position={[2.79, 5.494, 7.616]} rotation={[1.512, -0.673, -0.398]} scale={0.452} />
      <mesh geometry={nodes.Cube024.geometry} material={materials['Material.001']} position={[4.256, 5.362, 7.519]} rotation={[1.541, -0.51, -0.404]} scale={0.452} />
      <mesh geometry={nodes.Cube025.geometry} material={materials['Material.001']} position={[-1.121, 9.123, -6.973]} rotation={[-1.127, -0.189, 0.298]} scale={0.061} />
      <mesh geometry={nodes.Cube026.geometry} material={materials['Material.001']} position={[-0.977, 9.292, -6.929]} rotation={[-1.083, -0.179, 0.135]} scale={0.061} />
      <mesh geometry={nodes.Cube027.geometry} material={materials['Material.001']} position={[-1.118, 9.449, -6.827]} rotation={[-1.083, -0.179, 0.135]} scale={0.061} />
      <mesh geometry={nodes.Cube028.geometry} material={materials['Material.001']} position={[-0.812, 9.162, -7.021]} rotation={[-1.083, -0.179, 0.135]} scale={0.061} />
      <mesh geometry={nodes.Cube029.geometry} material={materials['Material.001']} position={[-0.731, 9.491, -6.866]} rotation={[-1.083, -0.179, 0.135]} scale={0.061} />
    </group>
  )
}

useGLTF.preload('/earth/earth.glb')
