/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/satellite/satellite.glb -t -r public 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder002: THREE.Mesh
    BezierCircle: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder004_1: THREE.Mesh
    Cylinder004_2: THREE.Mesh
    BezierCircle001: THREE.Mesh
    BezierCircle002: THREE.Mesh
    Cylinder006: THREE.Mesh
    Cube_1: THREE.Mesh
    Cube_2: THREE.Mesh
    BezierCircle003: THREE.Mesh
    Sphere_1: THREE.Mesh
    Sphere_2: THREE.Mesh
    BezierCircle004: THREE.Mesh
    BezierCircle005: THREE.Mesh
    Cylinder007: THREE.Mesh
    Sphere002: THREE.Mesh
    Cube002: THREE.Mesh
    Cube001: THREE.Mesh
    Cylinder008: THREE.Mesh
    Cylinder009: THREE.Mesh
    Cylinder010: THREE.Mesh
    Cylinder011: THREE.Mesh
    Cylinder012: THREE.Mesh
    Cylinder013: THREE.Mesh
  }
  materials: {
    ['03_Satellite I Template']: THREE.MeshStandardMaterial
    ['10_Satellite I Template']: THREE.MeshStandardMaterial
    ['01_Satellite I Template']: THREE.MeshStandardMaterial
    ['06_Satellite I Template']: THREE.MeshStandardMaterial
    ['09_Satellite I Template']: THREE.MeshStandardMaterial
    ['07_Satellite I Template']: THREE.MeshStandardMaterial
    ['11_Satellite I Template']: THREE.MeshStandardMaterial
    ['10_Satellite I Template']: THREE.MeshStandardMaterial
    ['02_Satellite I Template']: THREE.MeshStandardMaterial
  }
  animations: []
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Satellite(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/satellite/satellite.glb') as GLTFResult
  return (
    <group {...props} dispose={null} scale={10}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['03_Satellite I Template']} position={[0.603, 0.816, -0.157]} rotation={[-0.463, -0.283, -0.733]} scale={[0.461, 0.334, 0.461]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['10_Satellite I Template']} position={[0.746, 0.982, -0.193]} rotation={[-0.463, -0.283, -0.733]} scale={[0.371, 0.269, 0.371]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['01_Satellite I Template']} position={[0.87, 1.127, -0.225]} rotation={[-0.463, -0.283, -0.733]} scale={[0.308, 0.223, 0.308]} />
      <mesh geometry={nodes.BezierCircle.geometry} material={materials['06_Satellite I Template']} position={[0.367, 0.54, -0.096]} rotation={[-0.463, -0.283, -0.733]} scale={0.311} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['09_Satellite I Template']} position={[0.333, 0.5, -0.087]} rotation={[-0.463, -0.283, -0.733]} scale={[0.283, 0.205, 0.283]} />
      <group position={[-0.009, 0.103, 0]} rotation={[-0.463, -0.283, -0.733]} scale={[0.461, 0.334, 0.461]}>
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['03_Satellite I Template']} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['07_Satellite I Template']} />
      </group>
      <mesh geometry={nodes.BezierCircle001.geometry} material={materials['06_Satellite I Template']} position={[0.221, 0.371, -0.059]} rotation={[-0.463, -0.283, -0.733]} scale={0.311} />
      <mesh geometry={nodes.BezierCircle002.geometry} material={materials['06_Satellite I Template']} position={[0.383, -0.062, 0.21]} rotation={[-0.463, -0.283, -2.304]} scale={0.137} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['09_Satellite I Template']} position={[0.437, -0.101, 0.247]} rotation={[-0.463, -0.283, -2.304]} scale={0.115} />
      <group position={[0.828, -0.362, 0.584]} rotation={[-0.35, -0.376, -0.696]} scale={[0.461, 0.461, 0.138]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials['11_Satellite I Template']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['01_Satellite I Template']} />
      </group>
      <mesh geometry={nodes.BezierCircle003.geometry} material={materials['06_Satellite I Template']} position={[0.497, -0.142, 0.287]} rotation={[-0.463, -0.283, -2.304]} scale={0.137} />
      <group position={[-0.845, -0.871, 0.214]} rotation={[-0.463, -0.283, -0.733]} scale={0.461}>
        <mesh geometry={nodes.Sphere_1.geometry} material={materials['11_Satellite I Template']} />
        <mesh geometry={nodes.Sphere_2.geometry} material={materials['07_Satellite I Template']} />
      </group>
      <mesh geometry={nodes.BezierCircle004.geometry} material={materials['06_Satellite I Template']} position={[-0.41, -0.365, 0.103]} rotation={[-0.463, -0.283, -0.733]} scale={0.327} />
      <mesh geometry={nodes.BezierCircle005.geometry} material={materials['10_Satellite I Template']} position={[-0.87, -0.9, 0.221]} rotation={[-0.463, -0.283, -0.733]} scale={0.709} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['09_Satellite I Template']} position={[-0.628, -0.619, 0.159]} rotation={[-0.463, -0.283, -0.733]} scale={0.117} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['01_Satellite I Template']} position={[-1.141, -1.217, 0.29]} rotation={[-0.463, -0.283, -0.733]} scale={0.191} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['10_Satellite I Template']} position={[0.828, -0.362, 0.584]} rotation={[-0.35, -0.376, -0.696]} scale={[0.461, 0.461, 0.138]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['10_Satellite I Template']} position={[0.779, -0.319, 0.7]} rotation={[0.103, -0.068, 0.072]} scale={[0.538, 0.538, 0.161]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['02_Satellite I Template']} position={[-0.335, 1.362, 1.562]} scale={[0.125, 0.032, 0.125]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials['02_Satellite I Template']} position={[0.028, 1.174, 1.562]} scale={[0.085, 0.022, 0.085]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials['02_Satellite I Template']} position={[-1.16, 0.072, 1.562]} scale={[0.127, 0.032, 0.127]} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials['02_Satellite I Template']} position={[0.096, -0.796, 1.562]} scale={[0.05, 0.013, 0.05]} />
      <mesh geometry={nodes.Cylinder012.geometry} material={materials['02_Satellite I Template']} position={[1.131, 0.349, 1.562]} scale={[0.063, 0.016, 0.063]} />
      <mesh geometry={nodes.Cylinder013.geometry} material={materials['02_Satellite I Template']} position={[0.43, -1.01, 1.562]} scale={[0.157, 0.04, 0.157]} />
    </group>
  )
}

useGLTF.preload('/satellite/satellite.glb')
