/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/ufo/ufo.glb -t -r public 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BezierCircle: THREE.Mesh
    Sphere: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder005_1: THREE.Mesh
    Cylinder005_2: THREE.Mesh
    Sphere001: THREE.Mesh
    Cylinder011_1: THREE.Mesh
    Cylinder011_2: THREE.Mesh
    Cylinder005: THREE.Mesh
    BezierCircle001: THREE.Mesh
    Sphere002: THREE.Mesh
    BezierCircle002: THREE.Mesh
    Sphere003: THREE.Mesh
    BezierCircle003: THREE.Mesh
    Sphere004: THREE.Mesh
    BezierCircle004: THREE.Mesh
    Sphere005: THREE.Mesh
    BezierCircle005: THREE.Mesh
    Sphere006: THREE.Mesh
    BezierCircle006: THREE.Mesh
    Sphere007: THREE.Mesh
    BezierCircle007: THREE.Mesh
    Sphere008: THREE.Mesh
    Cylinder006: THREE.Mesh
    BezierCircle008: THREE.Mesh
    Sphere009: THREE.Mesh
    Cylinder: THREE.Mesh
    Sphere010: THREE.Mesh
    Cylinder007: THREE.Mesh
    Cube: THREE.Mesh
    Cylinder008: THREE.Mesh
    Cylinder009: THREE.Mesh
    Cylinder010: THREE.Mesh
    Cylinder011: THREE.Mesh
    Cylinder012: THREE.Mesh
    BezierCircle009: THREE.Mesh
    BezierCircle010: THREE.Mesh
  }
  materials: {
    ['04_UFO I Template']: THREE.MeshStandardMaterial
    ['08_UFO I Template']: THREE.MeshStandardMaterial
    ['04_UFO I Template']: THREE.MeshStandardMaterial
    ['02_UFO I Template']: THREE.MeshStandardMaterial
    ['05_UFO I Template']: THREE.MeshStandardMaterial
    ['01_UFO I Template']: THREE.MeshStandardMaterial
    ['07_UFO I Template']: THREE.MeshStandardMaterial
    ['06_UFO I Template']: THREE.MeshStandardMaterial
    ['03_UFO I Template']: THREE.MeshStandardMaterial
    ['09_UFO I Template']: THREE.MeshStandardMaterial
    ['01_Moon I Template']: THREE.MeshStandardMaterial
    ['01_Stars I Template']: THREE.MeshStandardMaterial
  }
  animations: []
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Ufo(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/ufo/ufo.glb') as GLTFResult
  return (
    <group {...props} dispose={null} scale={8} position={[0,10,0]}>
      <mesh geometry={nodes.BezierCircle.geometry} material={materials['04_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[0.432, 0, 0]} scale={0.189} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['08_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[-1.21, 0, 0]} scale={0.163} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['04_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[-0.135, 0, 0]} scale={0.795} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['02_UFO I Template']} position={[0, -0.225, -0.149]} rotation={[3.006, 0, Math.PI]} scale={[-0.795, -0.125, -0.795]} />
      <group position={[0, 0.414, -0.236]} rotation={[-0.135, 0, 0]} scale={[0.551, 0.13, 0.551]}>
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['04_UFO I Template']} />
        <mesh geometry={nodes.Cylinder005_2.geometry} material={materials['05_UFO I Template']} />
      </group>
      <mesh geometry={nodes.Sphere001.geometry} material={materials['01_UFO I Template']} position={[0, 0.687, -0.273]} rotation={[-0.135, 0, 0]} scale={0.436} />
      <group position={[0, -0.225, -0.149]} rotation={[3.006, 0, -Math.PI]} scale={[-0.795, -0.125, -0.795]}>
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials['07_UFO I Template']} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials['06_UFO I Template']} />
      </group>
      <mesh geometry={nodes.Cylinder005.geometry} material={materials['03_UFO I Template']} position={[0, -0.667, -0.088]} rotation={[-0.135, 0, 0]} scale={0.795} />
      <mesh geometry={nodes.BezierCircle001.geometry} material={materials['04_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[1.435, 1.004, -Math.PI / 2]} scale={0.189} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['08_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[-1.706, 0.497, Math.PI / 2]} scale={0.163} />
      <mesh geometry={nodes.BezierCircle002.geometry} material={materials['04_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[2.439, 0, Math.PI]} scale={0.189} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials['08_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[-2.203, 0, -Math.PI]} scale={0.163} />
      <mesh geometry={nodes.BezierCircle003.geometry} material={materials['04_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[1.435, -1.004, Math.PI / 2]} scale={0.189} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials['08_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[-1.706, -0.497, -Math.PI / 2]} scale={0.163} />
      <mesh geometry={nodes.BezierCircle004.geometry} material={materials['04_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[0.598, 0.639, -0.493]} scale={0.189} />
      <mesh geometry={nodes.Sphere005.geometry} material={materials['08_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[-1.34, 0.344, 0.721]} scale={0.163} />
      <mesh geometry={nodes.BezierCircle005.geometry} material={materials['04_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[2.273, 0.639, -2.649]} scale={0.189} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials['08_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[-2.072, 0.344, 2.42]} scale={0.163} />
      <mesh geometry={nodes.BezierCircle006.geometry} material={materials['04_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[2.273, -0.639, 2.649]} scale={0.189} />
      <mesh geometry={nodes.Sphere007.geometry} material={materials['08_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[-2.072, -0.344, -2.42]} scale={0.163} />
      <mesh geometry={nodes.BezierCircle007.geometry} material={materials['04_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[0.598, -0.639, 0.493]} scale={0.189} />
      <mesh geometry={nodes.Sphere008.geometry} material={materials['08_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[-1.34, -0.344, -0.721]} scale={0.163} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['09_UFO I Template']} position={[-0.001, -0.288, -0.137]} rotation={[-0.135, 0, 0]} scale={[0.837, 0.17, 0.837]} />
      <mesh geometry={nodes.BezierCircle008.geometry} material={materials['04_UFO I Template']} position={[0, 0.921, -0.31]} rotation={[-0.163, 0, 0]} scale={0.129} />
      <mesh geometry={nodes.Sphere009.geometry} material={materials['04_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[-0.135, 0, 0]} scale={0.118} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['09_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[-0.135, 0, 0]} scale={0.201} />
      <mesh geometry={nodes.Sphere010.geometry} material={materials['04_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[-0.135, 1.571, 0]} scale={0.118} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['09_UFO I Template']} position={[0, -0.484, -0.113]} rotation={[-0.135, 1.571, 0]} scale={0.201} />
      <mesh geometry={nodes.Cube.geometry} material={materials['01_Moon I Template']} position={[0, -2.004, 0]} rotation={[0.03, -0.12, 0.002]} scale={1.247} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['01_Stars I Template']} position={[0.72, 0.849, 1.562]} rotation={[0, 0, -0.186]} scale={[0.166, 0.042, 0.166]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials['01_Stars I Template']} position={[1.25, 0.345, 1.562]} rotation={[0, 0, 0.431]} scale={[0.083, 0.021, 0.083]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials['01_Stars I Template']} position={[-1.288, -0.382, 1.562]} rotation={[0, 0, 0.431]} scale={[0.086, 0.022, 0.086]} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials['01_Stars I Template']} position={[-0.985, 0.755, 1.562]} rotation={[0, 0, 0.431]} scale={[0.115, 0.029, 0.115]} />
      <mesh geometry={nodes.Cylinder012.geometry} material={materials['01_Stars I Template']} position={[-0.254, 1.217, 1.562]} rotation={[0, 0, 0.431]} scale={[0.065, 0.016, 0.065]} />
      <mesh geometry={nodes.BezierCircle009.geometry} material={materials['04_UFO I Template']} position={[0, -0.204, 0.79]} rotation={[-0.378, 0, 0]} scale={0.072} />
      <mesh geometry={nodes.BezierCircle010.geometry} material={materials['04_UFO I Template']} position={[0.93, -0.332, -0.132]} rotation={[-0.111, -0.055, 0.292]} scale={0.072} />
    </group>
  )
}

useGLTF.preload('/ufo/ufo.glb')
